name: deploy-infra

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'

  pull_request:
    branches: [main]
    paths:
      - 'terraform/**'

env:
  AWS_REGION: eu-west-2


jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    permissions:
      id-token: write
      contents: read


    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/bat-or-brolly-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Format Terraform
        # Check before formatting
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        # if github reference header is "main" and the event is push -> run tf apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan

